Repository PRIDE-Archive/pridepy, pull requests merged in 2024-10, with the labels that each got.

#37 major improvement to the ftp download method.
  benchmark/benchmark.sh
  benchmark/final_benchmark.csv
  pridepy/files/files.py
  pridepy/pridepy.py
  setup.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#38 bug fixing FTP url
  README.md
  pridepy/files/files.py
Labels: documentation, Review effort [1-5]: 2, bug_fix

#39 first iteration.
  benchmark/final_benchmark.csv
Labels: other

#41 Dev
  environment.yml
Labels: Review effort [1-5]: 2, dependencies

#42 Dev
  README.md
  benchmark/average_speed_location.png
  benchmark/benchmark.py
  benchmark/benchmark.svg
  benchmark/final_benchmark.csv
  benchmark/speed_by_method_location.svg
  paper/benchmark.svg
  paper/paper.md
  paper/paper.pdf
  paper/speed_by_method_location.svg
Labels: enhancement, Review effort [1-5]: 2

#44 Stream apis
  README.md
  environment.yml
  pridepy/files/files.py
  pridepy/pridepy.py
  pridepy/project/project.py
  pridepy/util/api_handling.py
  requirements.txt
  setup.py
Labels: enhancement, Review effort [1-5]: 3, dependencies
